### ISSUE TITLE
Hot reloading/Fast refreshing throws error: "_reactNativeMmkv.getString is not a function"

### ISSUE THREAD

**Issue by a-eid** [mrousavy/react-native-mmkv#24]
I weirdly get this error **somettimes** / **often** 

context: 

I check for the token right away globally in the app, could it be that MMKV is not available then ?

<img width="325" alt="Screen Shot 2021-03-09 at 3 21 30 PM" src="https://user-images.githubusercontent.com/19273413/110476845-20268f80-80eb-11eb-9caa-b1b080892d04.png">

**Comment by mrousavy** [comment]
MMKV is being initialized as soon as the bridge is being set (see [here](https://github.com/mrousavy/react-native-mmkv/blob/master/ios/Mmkv.mm#L118-L130)), afaik that is before JS code can be executed so it shouldn't be undefined. Could you try adding a breakpoint there to see what gets executed first?

**Comment by a-eid** [comment]
@mrousavy sorry, I'm not really sure how to do that, but will try and report back if I am successful.

**Comment by a-eid** [comment]
@mrousavy it does hit the `[MMKV initializeMMKV:nil];` line while on the native splash screen.

**Comment by a-eid** [comment]
please let me know if I can help more.

**Comment by mrousavy** [comment]
So apparently all of this happens when Hot-Reloading, not normally when starting.

**Comment by cristian05** [comment]
I'm getting the similar error in expo app: 

```shell
TypeError: _reactNativeMmkv.MMKV.getString is not a function. (In
 '_reactNativeMmkv.MMKV.getString(name)', '_reactNativeMmkv.MMKV.
getString' is undefined)
```

expo its supported?

**Comment by a-eid** [comment]
@cristian05 this package does not work with expo.

**Comment by mrousavy** [comment]
Can you check if the newest version (1.1.6) works for you? Note that it requires some additional installation steps, see [INSTALL.md](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md).

**Comment by a-eid** [comment]
when installing with reanimated 2, do we need to replace this ? 
```
protected JSIModulePackage getJSIModulePackage() {
   return new ReanimatedJSIModulePackage();
}
```

**Comment by a-eid** [comment]
also the app failed building on android 

```
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
290 actionable tasks: 271 executed, 19 up-to-date
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/react-native-geolocation-service/android/src/main/java/com/agontuk/RNFusedLocation/LocationUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-picker/picker/android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/AlsagheerJSIPackage.java:5: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvModule;
                          ^
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/MainApplication.java:44: error: cannot find symbol
            return new AlsagheerJSIPackage();
                       ^
  symbol: class AlsagheerJSIPackage
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/AlsagheerJSIPackage.java:16: error: cannot find symbol
        MmkvModule.install(jsContext, reactApplicationContext.getFilesDir().getAbsolutePath() + "/mmkv");
        ^
  symbol:   variable MmkvModule
  location: class AlsagheerJSIPackage
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/debug/java/com/alsagheer/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/react-native-geolocation-service/android/src/main/java/com/agontuk/RNFusedLocation/LocationUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-picker/picker/android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/AlsagheerJSIPackage.java:5: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvModule;
                          ^
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/MainApplication.java:44: error: cannot find symbol
            return new AlsagheerJSIPackage();
                       ^
  symbol: class AlsagheerJSIPackage
/Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/main/java/com/alsagheer/AlsagheerJSIPackage.java:16: error: cannot find symbol
        MmkvModule.install(jsContext, reactApplicationContext.getFilesDir().getAbsolutePath() + "/mmkv");
        ^
  symbol:   variable MmkvModule
  location: class AlsagheerJSIPackage
Note: /Users/ahmedeid/zeal/alsagheer-app-reactnative/android/app/src/debug/java/com/alsagheer/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (/Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/execa/index.js:174:9)
    at /Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (/Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/ahmedeid/zeal/alsagheer-app-reactnative/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by a-eid** [comment]
![Screen Shot 2021-03-27 at 5 46 12 AM](https://user-images.githubusercontent.com/19273413/112709187-bfa39a80-8ebf-11eb-9156-bf818306f569.png)

**Comment by mrousavy** [comment]
On which MMKV version are you? You need 1.1.6

**Comment by a-eid** [comment]
`^1.1.6` yes.

**Comment by alexreyes** [comment]
Can also confirm that the latest version doesn't work with Expo

**Comment by a-eid** [comment]
@alexreyes the library is not supported by expo.

**Comment by yelnar** [comment]
@a-eid did you find how to resolve your issue somehow?

**Comment by etomarat** [comment]
I have same issue! How to resolve this?

**Comment by jesseproudman** [comment]
It should be noted, this will also appear when using Codepush from Microsoft App Center.

**Comment by mrousavy** [comment]
@jesseproudman could you elaborate? I am using CodePush and MMKV works fine for me.

**Comment by jesseproudman** [comment]
@mrousavy Absolutely.

We've got a React-Native 0.64 app deployed via Test Flight, integrated with Appcenter / Codepush. 

We're seeing frequent exceptions being raised on app boot:

```
TypeError: f.MMKV.getString is not a function. (In 'f.MMKV.getString("veriff-status")', 'f.MMKV.getString' is undefined)
```

Many of these seem to be post a Codepush update which I would assume triggers hot reloading. Many of them also just appear on first boot based on the time stamps in the logs:

```
08:29:47 / Running "app" with {"rootTag":1,"initialProps":{}}
08:29:47 / [CodePush] Checking for update.
08:29:47 / TypeError: t.MMKV.getString is not a function. (In 't.MMKV.getString("user-email")', 't.MMKV.getString' is undefined)
```

**Comment by sauldom102** [comment]
@mrousavy I'm running into the same problem as @jesseproudman, we're not using Expo, just `react-native-unimodules`, it's really annoying these random crashes, probably as you said it's due to some race condition, any help would be appreciated, thanks in advance!

**Comment by mrousavy** [comment]
could anyone test if the changes in #92 fix this issue?

**Comment by jesseproudman** [comment]
@mrousavy giving this a go. thanks!

**Comment by jesseproudman** [comment]
This appears to have solved our issues. Will know more over the coming days.

**Comment by jesseproudman** [comment]
Just wanted to close the loop - We have not seen this particular error occur in production with this patch active.
