### ISSUE TITLE
MMKV with Expo

### ISSUE THREAD

**Issue by danilo-vieira** [mrousavy/react-native-mmkv#261]
Im trying to setup mmkv in my Expo project but still with the following error:
`Failed to create a new MMKV instance, the native initializer function does not exists`

What i do according #157:
- Install react-native-mmkv v1.3.2;
- Create a file `react-native-mmkv-plugin.js` at the project root;
- Paste [this gist content](https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2) inside `react-native-mmkv-plugin.js`;
- (Not sure this step is right) Create an `app.config.js` file and paste the following code according [expo guide](https://docs.expo.dev/guides/config-plugins/):
```js
module.exports = {
  name: "my app",
  plugins: ["./react-native-mmkv-plugin"]
}
```
- Run `expo prebuild` command and it shows:
```shell
What would you like your Android package name to be? ... com.app.myapp

Cannot automatically write to dynamic config at: app.config.js
Please add the following to your Expo config

{
  "android": {
    "package": "com.app.myapp"
  }
}
```
After that, i run the app and get the same error.

**Comment by intergalacticspacehighway** [comment]
Can you try this [solution](https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2#gistcomment-4009728)? 
If it doesn't work, I would recommend to check this [guide](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md) and compare it with your `android/` folder which is generated on running the prebuild command. The mmkv plugin is trying to implement this [installation instructions](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md).

**Comment by mrousavy** [comment]
Can you share the ADB logs?

**Comment by junaiddarajat** [comment]
I was having the same issue but got it to work; when you say you 'run' the application, how are you doing that?

This command works for me:
`npm i && expo prebuild --clean && expo run:android -d`

You can omit out npm install, but do run a prebuild with clean switch, this seems to be running for me, but then [now I'm facing an issue mentioned here](https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2#gistcomment-4014714)

**Comment by Hirbod** [comment]
MMKV 1.6.2 is working flawlessly on Expo SDK 44 with this config plugin:
https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2

**Comment by danilo-vieira** [comment]
@Hirbod i tryed to use MMKV 1.6.2, create a file `react-native-mmkv-plugin.js` at the project root and paste this content: https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2

Change app.json to this:
```json
{
  "expo": {
    "name": "mmkvtest",
    "slug": "mmkvtest",
    "version": "1.0.0",
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "com.danilovieira.mmkvtest"
    } // this is added after run `expo run:android`
  },
  "name": "mmkvtest",
  "plugins": [
    "./react-native-mmkv-plugin"
  ] // add 'plugins' line
}
```

When i run `expo prebuild --clean` and then `expo run:android` i got this log:
```
> Configure project :react-native-mmkv
MMKV: node_modules/ found at: C:\Users\danil\codes\testing\mmkvtest\node_modules
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Observed package id 'extras;google;Android_Emulator_Hypervisor_Driver' in inconsistent location 'C:\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver-2' (Expected 'C:\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver')
(node:17064) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\danil\codes\testing\mmkvtest\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

> Task :expo-file-system:processDebugManifest
C:\Users\danil\codes\testing\mmkvtest\node_modules\expo-file-system\android\src\main\AndroidManifest.xml:8:9-10:20 Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present

> Task :app:processDebugMainManifest
C:\Users\danil\codes\testing\mmkvtest\android\app\src\debug\AndroidManifest.xml:25:9-34:20 Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:25 to replace other declarations but no other declaration present

> Task :expo-modules-core:compileDebugKotlin
w: C:\Users\danil\codes\testing\mmkvtest\node_modules\expo-modules-core\android\src\main\java\expo\modules\kotlin\records\RecordTypeConverter.kt: (38, 13): Name shadowed: value

> Task :expo-modules-core:compileDebugJavaWithJavac
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-mmkv:downloadBoost
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

> Task :react-native-mmkv:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-mmkv:downloadFolly
Download https://github.com/facebook/folly/archive/v2020.01.13.00.tar.gz

> Task :react-native-mmkv:downloadGlog
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-mmkv:generateJsonModelDebug FAILED

FAILURE: Build failed with an exception.                                                       

* What went wrong:
Execution failed for task ':react-native-mmkv:generateJsonModelDebug'.
> C:\Users\danil\codes\testing\mmkvtest\node_modules\react-native-mmkv\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at C:\Users\danil\codes\testing\mmkvtest\node_modules\react-native-mmkv\android\CMakeLists.txt:22 (add_library):
    Syntax error in cmake code when parsing string

      C:\Users\danil\codes\testing\mmkvtest\node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\U'.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.    
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 1s
165 actionable tasks: 165 executed
C:\Users\danil\codes\testing\mmkvtest\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\danil\codes\testing\mmkvtest\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at spawnGradleAsync (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:83:18)
    at assembleAsync (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:57:16)
    at actionAsync (C:\Users\danil\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\runAndroid.ts:143:9)
```

@mrousavy sorry for delay

**Comment by danilo-vieira** [comment]
> Can you try this [solution](https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2#gistcomment-4009728)? If it doesn't work, I would recommend to check this [guide](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md) and compare it with your `android/` folder which is generated on running the prebuild command. The mmkv expo plugin is trying to implement [installation instructions](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md).

@intergalacticspacehighway according [this comment](https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2#gistcomment-4017338) it's working now.

**Comment by Hirbod** [comment]
@danilo-vieira kinda smells like windows weirdness. I am on Mac, not facing this issue :/

**Comment by danilo-vieira** [comment]
@Hirbod lol so im doing it right?

**Comment by danilo-vieira** [comment]
Thank you guys! The issue was only on Windows and [this solution](https://github.com/mrousavy/react-native-mmkv/issues/261#issuecomment-1005680424) works for me. Thanks @Hirbod

**Comment by rupakhetibinit** [comment]
I just ejected from expo and tried building this but get this error

```
* What went wrong:
Execution failed for task ':react-native-mmkv:generateJsonModelDebug'.
> D:\Binit Things\Programming\bare-react-native\recipetohome\node_modules\react-native-mmkv\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at D:\Binit Things\Programming\bare-react-native\recipetohome\node_modules\react-native-mmkv\android\CMakeLists.txt:22 (add_library):
    Syntax error in cmake code when parsing string

      D:\Binit Things\Programming\bare-react-native\recipetohome\node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\B'.
```

**Comment by intergalacticspacehighway** [comment]
@rupakhetibinit this looks like some kind of path issue on Windows. I don't have a windows system to test. This might sound weird but can you move your project to a folder that doesn't have spaces or try renaming `init Things` folder to `init-things`.

**Comment by rupakhetibinit** [comment]
@intergalacticspacehighway Unfortunately didn't work. I tried moving it to a location with no spaces in the file path yet still gives me this error.

**Comment by MOHAMED-LAAGUILI** [comment]
Failed to create a new MMKV instance: The native MMKV Module could not be found. * Make sure react-native-mmkv is correctly autolinked

It's also telling me I have new Architecture enabled, so it requires react-native-mmkv to be v 3.x.x
if i want to use the old arch i disabled newArch to false and down graded mmkv to v 2.x.x
still same error on android
im using expo
heres my config files @hirbod @mrousavy @danilo-vieira @intergalacticspacehighway @junaiddarajat  any help guys is appreciated

# package.json
```
{
  "name": "timetracker",
  "version": "1.0.0",
  "private": true,
  "packageManager": "pnpm@10.12.3",
  "main": "expo-router/entry",
  "scripts": {
    "start": "cross-env EXPO_NO_DOTENV=1 expo start",
    "prebuild": "cross-env EXPO_NO_DOTENV=1 pnpm expo prebuild",
    "android": "cross-env EXPO_NO_DOTENV=1 expo run:android",
    "ios": "cross-env EXPO_NO_DOTENV=1 expo run:ios",
    "web": "cross-env EXPO_NO_DOTENV=1 expo start --web",
    "xcode": "xed -b ios",
    "doctor": "npx expo-doctor@latest",
    "preinstall": "npx only-allow pnpm",
    "start:staging": "cross-env APP_ENV=staging pnpm run start",
    "prebuild:staging": "cross-env APP_ENV=staging pnpm run prebuild",
    "prebuild:development": "cross-env APP_ENV=development pnpm run prebuild",
    "android:staging": "cross-env APP_ENV=staging pnpm run android",
    "ios:staging": "cross-env APP_ENV=staging pnpm run ios",
    "start:production": "cross-env APP_ENV=production pnpm run start",
    "prebuild:production": "cross-env APP_ENV=production pnpm run prebuild",
    "android:production": "cross-env APP_ENV=production pnpm run android",
    "ios:production": "cross-env APP_ENV=production pnpm run ios",
    "build:development:ios": "cross-env APP_ENV=development EXPO_NO_DOTENV=1 eas build --profile development --platform ios",
    "build:development:android": "cross-env APP_ENV=development EXPO_NO_DOTENV=1 eas build --profile development --platform android--clear-cache",
    "build:staging:ios": "cross-env APP_ENV=staging EXPO_NO_DOTENV=1 eas build --profile staging --platform ios",
    "build:staging:android": "cross-env APP_ENV=staging EXPO_NO_DOTENV=1 eas build --profile staging --platform android ",
    "build:production:ios": "cross-env APP_ENV=production EXPO_NO_DOTENV=1 eas build --profile production --platform ios",
    "build:production:android": "cross-env APP_ENV=production EXPO_NO_DOTENV=1 eas build --profile production --platform android --clear-cache",
    "prepare": "husky",
    "app-release": "cross-env SKIP_BRANCH_PROTECTION=true np --no-publish --no-cleanup --no-release-draft",
    "version": "pnpm run prebuild && git add .",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "type-check": "tsc  --noemit",
    "lint:translations": "eslint ./src/translations/ --fix --ext .json  ",
    "test": "jest",
    "check-all": "pnpm run lint && pnpm run type-check && pnpm run lint:translations && pnpm run test",
    "test:ci": "pnpm run test --coverage",
    "test:watch": "pnpm run test --watch",
    "install-maestro": "curl -Ls 'https://get.maestro.mobile.dev' | bash",
    "e2e-test": "maestro test .maestro/ -e APP_ID=com.obytes.development"
  },
  "browser": {
    "better-sqlite3": false,
    "@nozbe/watermelondb/adapters/sqlite": false
  },
  "lint-staged": {
    "package.json": [
      "pnpm install --lockfile-only",
      "git add pnpm-lock.yaml"
    ],
    "pnpm-lock.yaml": [
      "git add pnpm-lock.yaml"
    ]
  },
  "dependencies": {
    "@expo/metro-runtime": "^5.0.4",
    "@expo/next-adapter": "^6.0.0",
    "@gorhom/bottom-sheet": "^5.0.5",
    "@hookform/resolvers": "^3.9.0",
    "@nozbe/watermelondb": "^0.28.0",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/netinfo": "11.4.1",
    "@react-navigation/drawer": "^7.3.9",
    "@react-navigation/native": "^7.1.6",
    "@shopify/flash-list": "1.7.6",
    "@shopify/react-native-skia": "2.0.0-next.4",
    "@tanstack/react-query": "^5.85.5",
    "@tanstack/react-table": "^8.21.3",
    "@wuba/react-native-echarts": "1.1.1-alpha.1",
    "app-icon-badge": "^0.1.2",
    "axios": "^1.7.5",
    "better-sqlite3": "^12.2.0",
    "clsx": "^2.1.1",
    "expo": "53.0.23",
    "expo-constants": "~17.1.6",
    "expo-crypto": "^14.1.5",
    "expo-dev-client": "~5.2.4",
    "expo-font": "~13.3.1",
    "expo-image": "~2.4.0",
    "expo-linear-gradient": "~14.1.5",
    "expo-linking": "~7.1.7",
    "expo-localization": "~16.1.6",
    "expo-router": "~5.1.6",
    "expo-splash-screen": "~0.30.10",
    "expo-sqlite": "^15.2.14",
    "expo-status-bar": "~2.2.3",
    "expo-system-ui": "~5.0.11",
    "expo-updates": "^0.28.17",
    "i18next": "^23.14.0",
    "lodash.memoize": "^4.1.2",
    "lottie-react-native": "7.2.2",
    "lucide-react-native": "^0.541.0",
    "moti": "^0.29.0",
    "nativewind": "^4.1.23",
    "next": "^15.5.0",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-error-boundary": "^4.0.13",
    "react-hook-form": "^7.53.0",
    "react-i18next": "^15.0.1",
    "react-icons": "^5.5.0",
    "react-native": "0.79.6",
    "react-native-chart-kit": "^6.12.0",
    "react-native-datatable-component": "^2.1.14",
    "react-native-edge-to-edge": "1.6.0",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-gifted-charts": "^1.4.64",
    "react-native-keyboard-controller": "^1.17.4",
    "react-native-mmkv": "^2.12.2",
    "react-native-paper": "^5.14.5",
    "react-native-reanimated": "~3.17.5",
    "react-native-reanimated-table": "^0.0.2",
    "react-native-restart": "0.0.27",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-table-component": "^1.2.2",
    "react-native-tableview-simple": "^4.4.1",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.20.0",
    "react-query": "^3.39.3",
    "react-query-kit": "^3.3.0",
    "tailwind-rn": "^4.2.0",
    "tailwind-variants": "^0.2.1",
    "uuid": "^13.0.0",
    "zod": "^3.23.8",
    "zustand": "^5.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.26.0",
    "@babel/helper-validator-identifier": "^7.27.1",
    "@commitlint/cli": "^19.2.2",
    "@commitlint/config-conventional": "^19.2.2",
    "@dev-plugins/react-query": "^0.0.7",
    "@eslint/eslintrc": "^3.3.1",
    "@eslint/js": "^9.28.0",
    "@expo/config": "~11.0.10",
    "@react-native-community/cli": "^20.0.2",
    "@testing-library/jest-dom": "^6.5.0",
    "@testing-library/react-native": "^12.7.2",
    "@types/i18n-js": "^3.8.9",
    "@types/invariant": "^2.2.37",
    "@types/jest": "^29.5.12",
    "@types/lodash.memoize": "^4.1.9",
    "@types/react": "~19.0.14",
    "@typescript-eslint/eslint-plugin": "^8.34.0",
    "@typescript-eslint/parser": "^8.34.0",
    "babel-plugin-module-resolver": "^5.0.2",
    "cross-env": "^7.0.3",
    "dotenv": "^16.4.5",
    "eslint": "^9.28.0",
    "eslint-config-expo": "^9.2.0",
    "eslint-config-prettier": "^10.1.5",
    "eslint-import-resolver-typescript": "^4.4.3",
    "eslint-plugin-i18n-json": "^4.0.1",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-prettier": "^5.4.1",
    "eslint-plugin-react-compiler": "19.1.0-rc.2",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "eslint-plugin-tailwindcss": "^3.18.0",
    "eslint-plugin-testing-library": "^7.5.2",
    "eslint-plugin-unicorn": "^59.0.1",
    "eslint-plugin-unused-imports": "^4.1.4",
    "husky": "^9.1.5",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-expo": "~53.0.10",
    "jest-junit": "^16.0.0",
    "lint-staged": "^15.2.9",
    "np": "^10.0.7",
    "prettier": "^3.3.3",
    "tailwindcss": "3.4.4",
    "ts-jest": "^29.1.2",
    "typescript": "~5.8.3",
    "typescript-eslint": "^8.34.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/user/repo-name.git"
  },
  "expo": {
    "doctor": {
      "reactNativeDirectoryCheck": {
        "listUnknownPackages": false,
        "exclude": [
          "react-native-restart",
          "@nozbe/watermelondb",
          "react-native-chart-kit",
          "react-native-table-component"
        ]
      }
    },
    "install": {
      "exclude": [
        "eslint-config-expo"
      ]
    }
  },
  "osMetadata": {
    "initVersion": "8.0.0"
  }
}
```

# eas.json
```
{
  "cli": {
    "version": ">= 3.8.1",
    "appVersionSource": "remote"
  },
  "build": {
    "production": {
      "autoIncrement": true,
      "channel": "production",
      "distribution": "store",
      "pnpm": "9.12.3",
      "ios": {
        "image": "latest"
      },
      "android": {
        "buildType": "app-bundle",
        "image": "latest"
      },
      "env": {
        "EXPO_NO_DOTENV": "1",
        "APP_ENV": "production",
        "FLIPPER_DISABLE": "1"
      }
    },
    "staging": {
      "channel": "staging",
      "distribution": "internal",
      "pnpm": "9.12.3",
      "ios": {
        "image": "latest"
      },
      "android": {
        "buildType": "apk",
        "image": "latest"
      },
      "env": {
        "APP_ENV": "staging",
        "EXPO_NO_DOTENV": "1",
        "FLIPPER_DISABLE": "1"
      }
    },
    "development": {
      "autoIncrement": true,
      "developmentClient": true,
      "distribution": "internal",
      "pnpm": "9.12.3",
      "ios": {
        "image": "latest"
      },
      "android": {
        "image": "latest"
      },
      "env": {
        "APP_ENV": "development",
        "EXPO_NO_DOTENV": "1"
      }
    },
    "simulator": {
      "pnpm": "9.12.3",
      "ios": {
        "simulator": true,
        "image": "latest"
      },
      "android": {
        "image": "latest"
      },
      "env": {
        "APP_ENV": "development",
        "EXPO_NO_DOTENV": "1"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```

# app.config.ts
```
import type { ConfigContext, ExpoConfig } from '@expo/config';
import type { AppIconBadgeConfig } from 'app-icon-badge/types';

import { ClientEnv, Env } from './env';

const appIconBadgeConfig: AppIconBadgeConfig = {
  enabled: Env.APP_ENV !== 'production',
  badges: [
    {
      text: Env.APP_ENV,
      type: 'banner',
      color: 'white',
    },
    {
      text: Env.VERSION.toString(),
      type: 'ribbon',
      color: 'white',
    },
  ],
};

const getBaseConfig = (config: any) => ({
  ...config,
  name: Env.NAME,
  description: `${Env.NAME} Mobile App for time tracking on projects`,
  owner: Env.EXPO_ACCOUNT_OWNER,
  scheme: Env.SCHEME,
  slug: Env.SLUG,
  version: Env.VERSION.toString(),
  orientation: 'portrait',
  icon: './assets/icon-new.png',
  userInterfaceStyle: 'automatic',
  newArchEnabled: false,
  experiments: {
    typedRoutes: true,
  },
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ['**/*'],
});

const getPlatformConfig = () => ({
  ios: {
    supportsTablet: true,
    bundleIdentifier: Env.BUNDLE_ID,
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon-new.png',
      backgroundColor: '#FFFFFF',
    },
    package: Env.PACKAGE,
  },
  web: {
    favicon: './assets/favicon-new.png',
    bundler: 'metro',
  },
});

const getPlugins = () => [
  [
    'expo-splash-screen',
    {
      backgroundColor: '#FFFFFF',
      image: './assets/splash-icon-new.png',
      imageWidth: 150,
    },
  ],
  [
    'expo-font',
    {
      fonts: ['./assets/fonts/Inter.ttf'],
    },
  ],
  'expo-localization',
  'expo-router',
  ['app-icon-badge', appIconBadgeConfig],
  ['react-native-edge-to-edge'],
];

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...getBaseConfig(config),
  ...getPlatformConfig(),
  plugins: getPlugins(),
  extra: {
    ...ClientEnv,
    eas: {
      projectId: Env.EAS_PROJECT_ID,
    },
  },
});
```

# storage.ts
```
import { MMKV } from 'react-native-mmkv';

export const storage = new MMKV({
  id: `user-time-tracker-storage`,
});

/*
import { MMKV, Mode } from 'react-native-mmkv'

export const storage = new MMKV({
  id: `user-${userId}-storage`,
  path: `${USER_DIRECTORY}/storage`,
  encryptionKey: 'hunter2',
  mode: Mode.MULTI_PROCESS,
  readOnly: false
})
 */
export function getItem<T>(key: string): T | null {
  const value = storage.getString(key);
  return value ? JSON.parse(value) || null : null;
}

export async function setItem<T>(key: string, value: T) {
  storage.set(key, JSON.stringify(value));
}

export async function removeItem(key: string) {
  storage.delete(key);
}

```
