### ISSUE TITLE
Could not resolve com.facebook.fbjni:fbjni:+. issue with expo bare workflow

### ISSUE THREAD

**Issue by a-eid** [mrousavy/react-native-mmkv#286]
```bash
> Task :react-native-mmkv:downloadGlog
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-mmkv:extractAARHeaders FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/username/oss/issues/mmkv-andorid-bug/node_modules/react-native-mmkv/android/build.gradle' line: 307

* What went wrong:
Execution failed for task ':react-native-mmkv:extractAARHeaders'.
> Could not resolve all files for configuration ':react-native-mmkv:extractHeaders'.
   > Could not resolve com.facebook.fbjni:fbjni:+.
     Required by:
         project :react-native-mmkv
      > Failed to list versions for com.facebook.fbjni:fbjni.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/fbjni/fbjni/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/facebook/fbjni/fbjni/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/facebook/fbjni/fbjni/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 55s
220 actionable tasks: 203 executed, 17 up-to-date
/Users/username/oss/issues/mmkv-andorid-bug/android/gradlew exited with non-zero code: 1
Error: /Users/username/oss/issues/mmkv-andorid-bug/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/username/n/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/username/n/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/username/n/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/username/n/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/username/n/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

unable to install `react-native-mmkv` with expo bare workflow 

fails with / without `react-native-reanimated` 

## repro repo

https://github.com/a-eid/mmkv-android-installation-issue

**Comment by mrousavy** [comment]
As the error message says, fbjni (a facebook library) cannot be downloaded, maybe their server is down.

**Comment by a-eid** [comment]
> As the error message says, fbjni (a facebook library) cannot be downloaded, maybe their server is down.

seems to be working now, thanks.
