### ISSUE TITLE
Uncaught ReferenceError when running on electron via react-native-web

### ISSUE THREAD

**Issue by maximilize** [mrousavy/react-native-mmkv#432]
We get the following error when running inside the renderer process of electron:

```
Uncaught ReferenceError: process is not defined
    at isJest (PlatformChecker.ts:2:3)
    at new MMKV (MMKV.ts:139:27)
```

The reason is that in a webbrowser (which is equal to the electron renderer process) does not have a global `process` variable.

This is our temporary fix:
```shell
sed -i "s/return process.env.JEST_WORKER_ID != null;/return false;/g" node_modules/react-native-mmkv/lib/*/PlatformChecker.js
```

**Comment by mrousavy** [comment]
Hi! Does MMKV work as expected in Electron? Aka does it correctly read from and write to `localStorage`?

**Comment by maximilize** [comment]
Aside from this bug it works as expected.

Since the "process" variable does not exist at all in a browser, I think this solution also will not succeed.

**Comment by mrousavy** [comment]
That should work: https://github.com/mrousavy/react-native-mmkv/commit/f693645e610e267c8f46f6e28e196a7f7fc964c9

**Comment by mrousavy** [comment]
Let me know if this change works for you, then I'll release an update

**Comment by maximilize** [comment]
I just tested, it exists on `globalThis`.
