### ISSUE TITLE
Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by ravisharnagat** [mrousavy/react-native-mmkv#458]
We have developed a npm package [Plugger](https://www.npmjs.com/package/@d11/plugger) which is using react-native-mmkv as a dependency. 

While using this package(as a dependency) inside a react-native app (using re.pack bundler), we are getting following error:

```
Possible Unhandled Promise Rejection (id: 0):
Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app.
Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app.
    at createMMKV (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:19177:1456)
    at MMKV (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:19157:1774)
    at Init (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4145:1447)
    at init (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4156:1105)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:2357)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:695)
    at _initModule (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:2131)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:2044)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:695)
    at getModule (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:4079:1989)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3925:2318)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3925:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3925:695)
    at GetModule (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3925:2148)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:2523)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:695)
    at _initStorageModule (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:2421)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:4831)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:695)
    at Init (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3881:4681)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:3287)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:695)
    at _initializePersistenceManager (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:3144)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:3521)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:1047)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:695)
    at initModules (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3848:3418)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3870:2060)
    at next (native)
    at fulfilled (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:3870:276)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/264n623y/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:22821:3828)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:22821:1801)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:22821:2525)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:22821:6758)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:21848:7803)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:21848:2900)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:21848:7367)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:21848:2854)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.customPro&modulesOnly=false&runModule=true:21848:2557)
```

Solution I've tried:
1. Added react-native as a peer dependency in our library, so that the native ios and android modules of mmkv get installed while installing the plugger package. No luck with this.

**Comment by mrousavy** [comment]
Hi!

React Native's autolinking system only knows dependencies that are in the app's package.json file. Therefore your users will need to manually run `yarn add react-native-mmkv`, then `pod install` in iOS folder.

Interested in what you are building though 🤔
