### ISSUE TITLE
FATAL EXCEPTION: create_react_context

### ISSUE THREAD

**Issue by KingAmo** [mrousavy/react-native-mmkv#5]
app crash:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fandengdushu.elearning-OgNUeAOCK1DzMhuUHXOymQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.fandengdushu.elearning-OgNUeAOCK1DzMhuUHXOymQ==/lib/arm, /data/app/com.fandengdushu.elearning-OgNUeAOCK1DzMhuUHXOymQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]] couldn't find "libcpp.so"
```
```
Process: com.fandengdushu.elearning, PID: 32418
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fandengdushu.elearning-eCUYOjb8H8IzYMhKFpsOkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.fandengdushu.elearning-eCUYOjb8H8IzYMhKFpsOkQ==/lib/arm, /data/app/com.fandengdushu.elearning-eCUYOjb8H8IzYMhKFpsOkQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]] couldn't find "libcpp.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.reactnativemmkv.MmkvModule.<clinit>(MmkvModule.kt:17)
        at com.reactnativemmkv.MmkvPackage.createNativeModules(MmkvPackage.kt:11)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by mrousavy** [comment]
Huh, weird. What RN version are you on?

**Comment by KingAmo** [comment]
this error dismissed after upgrade to `react-native-mmkv v1.0`

**Comment by dih7** [comment]
Hello, I've got a similar issue, let me know if you'd like me to open a new issue instead;

`FATAL EXCEPTION: create_react_context`

`FATAL EXCEPTION: create_react_context
Process: com.APP_NAME.demo, PID: 28201
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at com.reactnativemmkv.MmkvPackage.createNativeModules(Unknown Source:2)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/lib/x86, /data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/lib/x86, /data/app/com.APP_NAME.demo-Zex7HgOCzG-mYtRqTbI1sw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]`

I'm using react-native-mmkv 1.0.0 and RN 0.63.4 - do I need to be on 0.64?

**Comment by mrousavy** [comment]
@dih7 no you don't have to be on RN 64, does your project have Kotlin installed? I could refactor the code in this lib to java, since it's unnecessary to use Kotlin for 2 simple functions...

**Comment by mrousavy** [comment]
@dih7 let me know if v1.0.2 fixed the issue for you.

**Comment by dih7** [comment]
@mrousavy v1.0.2 works perfectly, thanks a lot!
