### ISSUE TITLE
Android 12 crash library libmmkv.so not found

### ISSUE THREAD

**Issue by dennned** [mrousavy/react-native-mmkv#774]
Hello,
Android build completes successfully. I have this fatal error only on Android 12. 

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
at java.lang.System.loadLibrary(System.java:1765)
at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:172)
at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327)
at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1104)
at java.lang.Thread.run(Thread.java:1012)`

The versions :
Gradle - 6.7.1
RN - 0.67.5
kesha-antonov/react-native-background-downloader - 3.1.1

It works perfectly in iOS though.
Thanks

**Comment by dennned** [comment]
The error log from logcat

> java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
> at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
> at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
> at java.lang.System.loadLibrary(System.java:1765)
> at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
> at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
> at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
> at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:172)
> at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
> at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
> at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
> at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462)
> at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433)
> at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327)
> at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
> at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1104)
> at java.lang.Thread.run(Thread.java:1012)
